const USER_STATUS = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  REJECTED: 'REJECTED'
};

const ROLE_NAME = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  VENDOR_ADMIN: 'VENDOR_ADMIN'
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_ERROR: 500
};

module.exports = { USER_STATUS, ROLE_NAME, HTTP_STATUS };